calendarium/urls.py
"""URLs for the ``calendarium`` app."""
from django.conf.urls import url

from . import views


urlpatterns = [
    # event views
    url(r'^event/create/$',
        views.EventCreateView.as_view(),
        name='calendar_event_create'),

    url(r'^event/(?P<pk>\d+)/$',
        views.EventDetailView.as_view(),
        name='calendar_event_detail'),

    url(r'^event/(?P<pk>\d+)/update/$',
        views.EventUpdateView.as_view(),
        name='calendar_event_update'),

    url(r'^event/(?P<pk>\d+)/delete/$',
        views.EventDeleteView.as_view(),
        name='calendar_event_delete'),

    # occurrence views
    url(r'^event/(?P<pk>\d+)/date/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$',
        views.OccurrenceDetailView.as_view(),
        name='calendar_occurrence_detail'),

    url(
        r'^event/(?P<pk>\d+)/date/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/update/$',  # NOPEP8
        views.OccurrenceUpdateView.as_view(),
        name='calendar_occurrence_update'),

    url(
        r'^event/(?P<pk>\d+)/date/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/delete/$',  # NOPEP8
        views.OccurrenceDeleteView.as_view(),
        name='calendar_occurrence_delete'),

    # calendar views
    url(r'^(?P<year>\d+)/(?P<month>\d+)/$',
        views.MonthView.as_view(),
        name='calendar_month'),

    url(r'^(?P<year>\d+)/week/(?P<week>\d+)/$',
        views.WeekView.as_view(),
        name='calendar_week'),

    url(r'^(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$',
        views.DayView.as_view(),
        name='calendar_day'),

    url(r'^get-events/$',
        views.UpcomingEventsAjaxView.as_view(),
        name='calendar_upcoming_events'),

    url(r'^$',
        views.CalendariumRedirectView.as_view(),
        name='calendar_current_month'),

]

filer/urls.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import

from django.conf.urls import url

from . import settings as filer_settings
from . import views

urlpatterns = [
    url(
        filer_settings.FILER_CANONICAL_URL + r'(?P<uploaded_at>[0-9]+)/(?P<file_id>[0-9]+)/$',  # flake8: noqa
        views.canonical,
        name='canonical'
    ),
]

popi/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^institut/', include('institut.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^calendar/', include('calendarium.urls')),
]

calendarium/forms.py
"""Forms for the ``calendarium`` app."""
from django import forms
from django.contrib.auth.models import User
from django.forms.models import model_to_dict
from django.utils.timezone import datetime, timedelta

from .constants import OCCURRENCE_DECISION_CHOICESS, OCCURRENCE_DECISIONS
from .models import Event, Occurrence


class OccurrenceForm(forms.ModelForm):
    """A form for the ``Occurrence`` model."""
    decision = forms.CharField(
        widget=forms.Select(choices=OCCURRENCE_DECISION_CHOICESS),
    )

    cancelled = forms.BooleanField(
        widget=forms.HiddenInput,
        required=False,
    )

    original_start = forms.DateTimeField(
        widget=forms.HiddenInput,
    )

    original_end = forms.DateTimeField(
        widget=forms.HiddenInput,
    )

    event = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Event.objects.all(),
    )

    class Meta:
        model = Occurrence
        exclude = []

    def save(self):
        cleaned_data = self.cleaned_data
        if cleaned_data['decision'] == OCCURRENCE_DECISIONS['all']:
            changes = dict(
                (key, value) for key, value in iter(cleaned_data.items())
                if value != self.initial.get(key) and self.initial.get(key))
            event = self.instance.event
            # for each field on the event, check for new data in cleaned_data
            for field_name in [field.name for field in event._meta.fields]:
                value = changes.get(field_name)
                if value:
                    setattr(event, field_name, value)
            event.save()

            # repeat for persistent occurrences
            for occ in event.occurrences.all():
                for field_name in [field.name for field in occ._meta.fields]:
                    value = changes.get(field_name)
                    if value:
                        # since we can't just set a new datetime, we have to
                        # adjust the datetime fields according to the changes
                        # on the occurrence form instance
                        if type(value) != datetime:
                            setattr(occ, field_name, value)
                        else:
                            initial_time = self.initial.get(field_name)
                            occ_time = getattr(occ, field_name)
                            delta = value - initial_time
                            new_time = occ_time + delta
                            setattr(occ, field_name, new_time)
                occ.save()

            # get everything from initial and compare to cleaned_data to
            # retrieve what has been changed
            # apply those changes to the persistent occurrences (and the main
            # event)
        elif cleaned_data['decision'] == OCCURRENCE_DECISIONS['this one']:
            self.instance.save()
        elif cleaned_data['decision'] == OCCURRENCE_DECISIONS['following']:
            # get the changes
            changes = dict(
                (key, value) for key, value in iter(cleaned_data.items())
                if value != self.initial.get(key) and self.initial.get(key))

            # change the old event
            old_event = self.instance.event
            end_recurring_period = self.instance.event.end_recurring_period
            old_event.end_recurring_period = self.instance.start - timedelta(
                days=1)
            old_event.save()

            # the instance occurrence holds the info for the new event, that we
            # use to update the old event's fields
            new_event = old_event
            new_event.end_recurring_period = end_recurring_period
            new_event.id = None
            event_kwargs = model_to_dict(self.instance)
            for field_name in [field.name for field in new_event._meta.fields]:
                if (field_name == 'created_by' and
                        event_kwargs.get('created_by')):
                    value = User.objects.get(pk=event_kwargs.get(field_name))
                elif field_name in ['rule', 'category']:
                    continue
                else:
                    value = event_kwargs.get(field_name)
                if value:
                    setattr(new_event, field_name, value)
            new_event.save()

calendarium/views.py
"""Views for the ``calendarium`` app."""
import calendar
from dateutil.relativedelta import relativedelta

from django.contrib.auth.decorators import permission_required
from django.core.urlresolvers import reverse
from django.forms.models import model_to_dict
from django.http import Http404, HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.utils.timezone import datetime, now, timedelta, utc
from django.utils.translation import ugettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    RedirectView,
    TemplateView,
    UpdateView,
)

from .constants import OCCURRENCE_DECISIONS
from .forms import OccurrenceForm
from .models import EventCategory, Event, Occurrence
from .settings import SHIFT_WEEKSTART
from .utils import monday_of_week


class CategoryMixin(object):
    """Mixin to handle category filtering by category id."""
    def dispatch(self, request, *args, **kwargs):
        if request.GET.get('category'):
            try:
                category_id = int(request.GET.get('category'))
            except ValueError:
                pass
            else:
                try:
                    self.category = EventCategory.objects.get(pk=category_id)
                except EventCategory.DoesNotExist:
                    pass
        return super(CategoryMixin, self).dispatch(request, *args, **kwargs)

    def get_category_context(self, **kwargs):
        context = {'categories': EventCategory.objects.all()}
        if hasattr(self, 'category'):
            context.update({'current_category': self.category})
        return context


class CalendariumRedirectView(RedirectView):
    """View to redirect to the current month view."""
    permanent = False

    def get_redirect_url(self, **kwargs):
        return reverse('calendar_month', kwargs={'year': now().year,
                                                 'month': now().month})


class MonthView(CategoryMixin, TemplateView):
    """View to return all occurrences of an event for a whole month."""
    template_name = 'calendarium/calendar_month.html'

    def dispatch(self, request, *args, **kwargs):
        self.month = int(kwargs.get('month'))
        self.year = int(kwargs.get('year'))
        if self.month not in range(1, 13):
            raise Http404
        if request.method == 'POST':
            if request.POST.get('next'):
                new_date = datetime(self.year, self.month, 1) + timedelta(
                    days=31)
                kwargs.update({'year': new_date.year, 'month': new_date.month})
                return HttpResponseRedirect(
                    reverse('calendar_month', kwargs=kwargs))
            elif request.POST.get('previous'):
                new_date = datetime(self.year, self.month, 1) - timedelta(
                    days=1)
                kwargs.update({'year': new_date.year, 'month': new_date.month})
                return HttpResponseRedirect(
                    reverse('calendar_month', kwargs=kwargs))
            elif request.POST.get('today'):
                kwargs.update({'year': now().year, 'month': now().month})
                return HttpResponseRedirect(
                    reverse('calendar_month', kwargs=kwargs))
        if request.is_ajax():
            self.template_name = 'calendarium/partials/calendar_month.html'
        return super(MonthView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        firstweekday = 0 + SHIFT_WEEKSTART
        while firstweekday < 0:
            firstweekday += 7
        while firstweekday > 6:
            firstweekday -= 7

        ctx = self.get_category_context()
        month = [[]]
        week = 0
        start = datetime(year=self.year, month=self.month, day=1, tzinfo=utc)
        end = datetime(
            year=self.year, month=self.month, day=1, tzinfo=utc
        ) + relativedelta(months=1)

        all_occurrences = Event.objects.get_occurrences(
            start, end, ctx.get('current_category'))
        cal = calendar.Calendar()
        cal.setfirstweekday(firstweekday)
        for day in cal.itermonthdays(self.year, self.month):
            current = False
            if day:
                date = datetime(year=self.year, month=self.month, day=day,
                                tzinfo=utc)
                occurrences = filter(
                    lambda occ, date=date: occ.start.replace(
                        hour=0, minute=0, second=0, microsecond=0) == date,
                    all_occurrences)
                if date.date() == now().date():
                    current = True
            else:
                occurrences = []
            month[week].append((day, occurrences, current))
            if len(month[week]) == 7:
                month.append([])
                week += 1
        calendar.setfirstweekday(firstweekday)
        weekdays = [_(header) for header in calendar.weekheader(10).split()]
        ctx.update({'month': month, 'date': date, 'weekdays': weekdays})
        return ctx


class WeekView(CategoryMixin, TemplateView):
    """View to return all occurrences of an event for one week."""
    template_name = 'calendarium/calendar_week.html'

    def dispatch(self, request, *args, **kwargs):
        self.week = int(kwargs.get('week'))
        self.year = int(kwargs.get('year'))
        if self.week not in range(1, 53):
            raise Http404
        if request.method == 'POST':
            if request.POST.get('next'):
                date = monday_of_week(self.year, self.week) + timedelta(days=7)
                kwargs.update(
                    {'year': date.year, 'week': date.date().isocalendar()[1]})
                return HttpResponseRedirect(
                    reverse('calendar_week', kwargs=kwargs))
            elif request.POST.get('previous'):
                date = monday_of_week(self.year, self.week) - timedelta(days=7)
                kwargs.update(
                    {'year': date.year, 'week': date.date().isocalendar()[1]})
                return HttpResponseRedirect(
                    reverse('calendar_week', kwargs=kwargs))
            elif request.POST.get('today'):
                kwargs.update({
                    'year': now().year,
                    'week': now().date().isocalendar()[1],
                })
                return HttpResponseRedirect(
                    reverse('calendar_week', kwargs=kwargs))
        if request.is_ajax():
            self.template_name = 'calendarium/partials/calendar_week.html'
        return super(WeekView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = self.get_category_context()
        date = monday_of_week(self.year, self.week) + relativedelta(
            days=SHIFT_WEEKSTART)
        week = []
        day = SHIFT_WEEKSTART
        start = date
        end = date + relativedelta(days=7 + SHIFT_WEEKSTART)
        all_occurrences = Event.objects.get_occurrences(
            start, end, ctx.get('current_category'))
        while day < 7 + SHIFT_WEEKSTART:
            current = False
            occurrences = filter(
                lambda occ, date=date: occ.start.replace(
                    hour=0, minute=0, second=0, microsecond=0) == date,
                all_occurrences)
            if date.date() == now().date():
                current = True
            week.append((date, occurrences, current))
            day += 1
            date = date + timedelta(days=1)
        ctx.update({'week': week, 'date': date, 'week_nr': self.week})
        return ctx


class DayView(CategoryMixin, TemplateView):
    """View to return all occurrences of an event for one day."""
    template_name = 'calendarium/calendar_day.html'

    def dispatch(self, request, *args, **kwargs):
        self.day = int(kwargs.get('day'))
        self.month = int(kwargs.get('month'))
        self.year = int(kwargs.get('year'))
        try:
            self.date = datetime(year=self.year, month=self.month,
                                 day=self.day, tzinfo=utc)
        except ValueError:
            raise Http404
        if request.method == 'POST':
            if request.POST.get('next'):
                date = self.date + timedelta(days=1)
                kwargs.update(
                    {'year': date.year, 'month': date.month, 'day': date.day})
                return HttpResponseRedirect(
                    reverse('calendar_day', kwargs=kwargs))
            elif request.POST.get('previous'):
                date = self.date - timedelta(days=1)
                kwargs.update({
                    'year': date.year,
                    'month': date.month,
                    'day': date.day,
                })
                return HttpResponseRedirect(
                    reverse('calendar_day', kwargs=kwargs))
            elif request.POST.get('today'):
                kwargs.update({
                    'year': now().year,
                    'month': now().month,
                    'day': now().day,
                })
                return HttpResponseRedirect(
                    reverse('calendar_day', kwargs=kwargs))
        if request.is_ajax():
            self.template_name = 'calendarium/partials/calendar_day.html'
        return super(DayView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = self.get_category_context()
        occurrences = Event.objects.get_occurrences(
            self.date, self.date, ctx.get('current_category'))
        ctx.update({'date': self.date, 'occurrences': occurrences})
        return ctx


class EventDetailView(DetailView):
    """View to return information of an event."""
    model = Event


class EventMixin(object):
    """Mixin to handle event-related functions."""
    model = Event
    fields = '__all__'

    @method_decorator(permission_required('calendarium.add_event'))

calendarium/templates/calendarium/calendar_day.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<font color="#2F2F2F"><h2>-</h2></font>
<h1>{{ date|date:'D d/m' }}</h1>
{% include "calendarium/partials/category_list.html" %}
<form action="." method="post">
    {% csrf_token %}
    <font color="#2F2F2F"><input type="submit" name="previous" value="{% trans "Précédent" %}" /></font>
    <font color="#2F2F2F"><input type="submit" name="next" value="{% trans "Prochain" %}" /></font>
    <font color="#2F2F2F"><input type="submit" name="today" value="{% trans "Aujourd'hui" %}" /></font>
</form>
<table class="table">
    <tr>
        <h1><th>{{ date|date:'D d/m' }}</th></h1>
    </tr>
        {% for occurrence in occurrences %}
            <tr><td>{{ occurrence }}</td></tr>
        {% endfor %}
</table>
{% endblock %}

calendarium/templates/calendarium/calendar_month.html
{% extends "base.html" %}
{% load i18n calendarium_tags %}


{% block main %}

<font color="#2F2F2F"><h2>-</h2></font>
<h1>{{ date|date:"F Y" }}</h1>
{% include "calendarium/partials/category_list.html" %}
<form action="." method="post">
    {% csrf_token %}
    <font color="#2F2F2F"><input class="btn btn-default" type="submit" name="previous" value="{% trans "Précédent" %}" /></font>
    <font color="#2F2F2F"><input class="btn btn-default" type="submit" name="next" value="{% trans "Prochain" %}" /></font>
    <font color="#2F2F2F"><input class="btn btn-default" type="submit" name="today" value="{% trans "Aujourd'hui" %}" /></font>
    {% if request.user.is_staff %}
        <a href="{% url "calendar_event_create" %}">{% trans "Create new event" %}</a>
    {% endif %}
</form>
<br>


<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#id-popuprdv">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nouveau RDV
</button>


<table class="table" id="calendar-month">
    <tr>
        <th></th>
        {% for weekday in weekdays %}
            <th>{{ weekday }}</th>
        {% endfor %}
    </tr>
    {% for week in month %}
        {% if week %}
            <tr>
                <td class="calendarium-week-link"><a href="{{ date|get_week_URL:week.0.0 }}">{% trans "Voir semaine" %}</a></td>
                {% for day, occurrences, current in week %}
                    <td class="{% if day == 0 %}calendarium-empty{% elif current %}calendarium-current{% else %}calendarium-day{% endif %}">
                        <div class="calendarium-relative">
                            {% if day != 0 %}
                                <span class="calendarium-date">{{ day }}</span>
                                {% for occurrence in occurrences %}
                                    <p class="alert" style="background-color: {{ occurrence.event.category.color }}">
{#                                    <p>#}
                                        <a title="{{ occurrence }}" href="{% url "calendar_occurrence_detail" pk=occurrence.event.pk year=occurrence.start.year month=occurrence.start.month day=occurrence.start.day %}">{{ occurrence|truncatechars:22 }}</a>
                                    </p>
{#                                    </p>#}
                                {% endfor %}
                            {% endif %}
                        </div>
                    </td>
                {% endfor %}
            </tr>
        {% endif %}
    {% endfor %}
</table>


<div class="modal fade" id="id-popuprdv" tabindex="-1" role="dialog" aria-labelledby="titrePopUp" aria-hidden="true">

      <div class="modal-dialog">

        <div class="modal-content">

          <!-- le titre de la popup -->
          <div class="modal-header">
          <font color ='black'><h2 class="modal-title" id="titrePopUp">Nouveau RDV</font>
          <!-- lla croix de fermeture de la popup -->
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button> </h2>
          </div>
            <form action="{% url "saverdv" %}" method="post">
                {% csrf_token %}
                <font color="black">
                <div class="modal-body">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-4"><h4>Nom du client</h4></div>
                            <div class="col-md-4">
                                <input type="text" class="form-control" name="title" id="title">
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-md-4"><h4>Jour</h4></div>
                            <div class="col-md-4">
                                <input type="text" name="datepickerrdv" id="datepickerrdv" class="form-control" value=""/>
                                <script language="javascript">
                                today = new Date();
                                if(today.getDate() < 10)
                                {
                                    if(today.getMonth() < 10)
                                    {
                                        document.getElementById('datepickerrdv').value = (today.getYear()+1900)+"-"+"0"+(today.getMonth()+1)+"-"+"0"+today.getDate();
                                    }
                                    else
                                    {

                                        document.getElementById('datepickerrdv').value = (today.getYear()+1900)+"-"+(today.getMonth()+1)+"-"+"0"+today.getDate();
                                    }
                                }
                                else if(today.getMonth() < 10)
                                {
                                    document.getElementById('datepickerrdv').value = (today.getYear()+1900)+"-"+"0"+(today.getMonth()+1)+"-"+today.getDate();
                                }
                                else
                                {
                                    document.getElementById('datepickerrdv').value = (today.getYear()+1900)+"-"+(today.getMonth()+1)+"-"+today.getDate();
                                }
                                </script>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-md-4"><h4>Heure de début</h4></div>
                            <div class="col-md-4">
                                <input type="text" class="form-control" id = "input-a" name="heure_start" value="">
                                <script language="javascript">
                                today = new Date();
                                if(today.getHours() < 10)
                                {
                                    if(today.getMinutes() < 10)
                                    {
                                        document.getElementById('input-a').value = "0"+today.getHours()+":0"+today.getMinutes();
                                    }
                                    else
                                    {
                                        document.getElementById('input-a').value = "0"+today.getHours()+":"+today.getMinutes();
                                    }
                                }
                                else if(today.getMinutes() < 10)
                                {
                                    document.getElementById('input-a').value = today.getHours()+":0"+today.getMinutes();
                                }
                                else
                                {
                                    document.getElementById('input-a').value = today.getHours()+":"+today.getMinutes();
                                }
                                </script>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-md-4"><h4>Heure de fin</h4></div>
                            <div class="col-md-4">
                                <input type="text" class="form-control" id = "input-b" name="heure_end" value="">
                                <script language="javascript">
                                today = new Date();
                                if((today.getHours()+1) < 10)
                                {
                                    if(today.getMinutes() < 10)
                                    {
                                        document.getElementById('input-b').value = "0"+(today.getHours()+1)+":0"+today.getMinutes();
                                    }
                                    else
                                    {
                                        document.getElementById('input-b').value = "0"+(today.getHours()+1)+":"+today.getMinutes();
                                    }
                                }
                                else if(today.getMinutes() < 10)
                                {
                                    document.getElementById('input-b').value = (today.getHours()+1)+":0"+today.getMinutes();
                                }
                                else
                                {
                                    document.getElementById('input-b').value = (today.getHours()+1)+":"+today.getMinutes();
                                }
                                </script>
                            </div>
                        </div>




                        <script>
                        var input_s = $('#input-a');
                        input_s.clockpicker({
                            autoclose: true
                        });
                        var input_e = $('#input-b');
                        input_e.clockpicker({
                            autoclose: true
                        });
                        </script>

                        <div class="row">
                            <div class="col-md-4"><h4>Catégorie</h4></div>
                            <div class="col-md-4">
                                <select class="selectpicker" data-live-search="true" name="description">
                                    {% include "calendarium/partials/category_list2.html" %}
                                </select>
                            </div>
                        </div>




                    </div>
                </div>
                </font>

            <div class="modal-footer">
                <input type="submit" value="Enregistrer" class="btn btn-success pull-left"/>
                <a href="/calendar/" class="btn btn-danger pull-left">Annuler</a>
            </div>
            </form>


            </div>
        </div>
    </div>













{% render_upcoming_events 5 current_category %}
{% endblock %}

calendarium/templates/calendarium/calendar_week.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<font color="#2F2F2F"><h2>-</h2></font>
<h1>{% trans "Occurrences" %}</h1>
{% include "calendarium/partials/category_list.html" %}
<form action="." method="post">
    {% csrf_token %}
    <font color="#2F2F2F"><input type="submit" name="previous" value="{% trans "Précédent" %}" /></font>
    <font color="#2F2F2F"><input type="submit" name="next" value="{% trans "Prochain" %}" /></font>
    <font color="#2F2F2F"><input type="submit" name="today" value="{% trans "Aujourd'hui" %}" /></font>
</form>
<table class="table" id="calendar-week">
    <tr>
        {% for date, occurrences, current in week %}
            <th><a href="{% url "calendar_day" year=date|date:'Y' month=date|date:'m' day=date|date:'d' %}">{{ date|date:'D d/m' }}</a></th>
        {% endfor %}
    </tr>
    <tr>
        {% for date, occurrences, current in week %}
            <td class="{% if current %}calendarium-current{% endif %}">
                <div class="calendarium-relative">
                    <span class="calendarium-day-dame">{{ date|date:'D d/m' }}</span>
                    <a class="calendarium-day-link" href="{% url "calendar_day" year=date|date:'Y' month=date|date:'m' day=date|date:'d' %}">{% trans "Voir journée" %}</a>
                    <br>
                    {% for occurrence in occurrences %}
                        <p>
                            <a href="{% url "calendar_occurrence_detail" pk=occurrence.event.pk year=occurrence.start.year month=occurrence.start.month day=occurrence.start.day %}">{{ occurrence|truncatechars:22 }}</a>
                        </p>
                    {% endfor %}
                </div>
            </td>
        {% endfor %}
    </tr>
</table>
{% endblock %}

calendarium/templates/calendarium/event_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1>{% trans "Delete" %} {{ object }}</h1>
<form method="post" action=".">
    {% csrf_token %}
    {% trans "Do you really want to delete this event?" %}
    <input type="submit" value="{% trans "Delete" %}" />
</form>
{% endblock %}

calendarium/templates/calendarium/event_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1><font color="#2F2F2F">-</font></h1>
<h1>{{ object }}</h1>
<table>
    <tr>
        <th>{% trans "Heure de début" %}</th>
        <td>{{ object.start }}</td>
    </tr>
    <tr>
        <th>{% trans "Heure de fin" %}</th>
        <td>{{ object.end }}</td>
    </tr>
    <tr>
        <th>{% trans "Type de soin" %}</th>
        <td>{{ object.category }}</td>
    </tr>
    <tr>
        <th>{% trans "Nom du client" %}</th>
        <td>{{ object.title }}</td>
    </tr>
</table>
<a href="javascript:history.back();">{% trans "Retour" %}</a>
{% if request.user.is_staff %}
    <a href="{% url "calendar_event_update" pk=object.pk %}">{% trans "Editer" %}</a>
    <a href="{% url "calendar_event_delete" pk=object.pk %}">{% trans "Supprimer" %}</a>
{% endif %}
{% endblock %}

calendarium/templates/calendarium/occurrence_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1>{% trans "Delete" %} {{ object }}</h1>
<form method="post" action="{% url "calendar_occurrence_delete" pk=object.event.pk year=object.start.year month=object.start.month day=object.start.day %}">
    {% csrf_token %}
    <p>
        <label for="id_event">{% trans "Decision" %}:</label>
        <select name="decision">
            {% for decision in decisions %}
                <option value="{{ decision }}">{{ decision }}</option>
            {% endfor %}
        </select>
    </p>
    <a href="{% url "calendar_occurrence_update" pk=object.event.pk year=object.start.year month=object.start.month day=object.start.day %}">{% trans "Back" %}</a>
    <input type="submit" value="{% trans "Delete" %}" />
</form>
{% endblock %}

calendarium/templates/calendarium/upcoming_events.html
<ul>
    {% for occurrence in occurrences %}
        <li>{{ occurrence.title }}</li>
    {% endfor %}
</ul>